name: Deploy Discord Bot

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1052750188063/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-lugabot@turing-course-388300.iam.gserviceaccount.com"
      
      - name: SSH into VM and restart bot
        run: |
            gcloud compute ssh govertfabiancarre@bot-provider --zone us-east1-b --command "tmux ls"